### PR TITLE
Upgraded Deps and NGRX 4.x.x

### PR DESCRIPTION
**Pull request by Kaffiend**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Updates Angular, NGRX, and Typescript with current versions.

* **What is the new behavior (if this is a feature change)?**

* **Other information**:
In `app.module.ts` HMR init function used to stringify state and log it to the console. This needs to be revisited if its really desired. A replacer or serializer will need to be used, `@ngrx/router-store` includes `routerState` which contains circular structure.

### CODE REVIEW

**Comment by Kaffiend** [comment]
fixes #6

**Comment by Kaffiend** [comment]
this may resolve #5 as well...

**Comment by Kaffiend** [comment]
need to update the tests.

**Comment by Kaffiend** [comment]
fixing AOT

**Comment by Kaffiend** [comment]
@colinskow looks like everything else is fine, just AOT needs some love. I'll take another look at this tomorrow. unless someone else can figure it out before hand.

**Comment by Kaffiend** [comment]
currently `ngrx-store-freeze` is not compatible with v4, see [here](https://github.com/DorianGrey/ng-webpack-template/pull/5) so I removed it, until it can be updated. I suspect this PR will remain open and we can update it as NGRX and dependent libs progress.

**Comment by colinskow** [comment]
Thank you very much! I will have a chance to review next Tues or Weds.

**Comment by colinskow** [comment]
How is the progress on this going? It looks like AngularClass now has a new HMR loader that works out of the box with ngrx 4.

@Kaffiend are you interested in finishing this, or should I go ahead. It looks fairly simple.

**Comment by Css-IanM** [comment]
I have been swamped, of late. I might be able to get to this, this weekend. Unless you can find time before then. I dont mind either way. I havent seen the new loader as i've been busy on some work projects. Ill have to check that out. This PR works with everything but AOT i think, if i recall correctly. But would need updated with the new loader it sounds like.

**Comment by Kaffiend** [comment]
@colinskow I looked at the HMR Loader. I don’t see anything other than the my PR explaining how to hook into NGRX4 with the existing loader.

Ian Mackie
Lead Developer
Complete System Support, Inc.
O: 304.428.2143
F: 304.428.2145

**Comment by colinskow** [comment]
The main issue is that the build needs to pass, including with AoT. It looks like `ngrx-store-freeze` is still not ready for 4.0. Perhaps we can stub the code in but comment it out until ready.

Over the next few days I'll take a look at your PR and compare it to the official migration guide to ensure everything is standard. We can merge when the build is passing.

**Comment by Css-IanM** [comment]
I have the AOT code on my own branch in a separate project I just need to update the PR here. I’ve also yet to update the router store with the new serializer, which was release and updated since the last PR here. There is still some yet to do.

Ian Mackie
Lead Developer
Complete System Support, Inc.

**Comment by Kaffiend** [comment]
i'll try to get to this either later this evening or tomorrow morning, Had some time sensitive issues crop up in some old COBOL apps that requires my attention for the better part of this weekend unfortunately.

**Comment by colinskow** [comment]
@Kaffiend thank you very much for your work on this. Using your changes as a guide I was able to work things out and get the build passing, even with `store-freeze` working. However I did a slightly different implementation so it was easier for me to copy and paste from your code than to try to rebase your fork.

I will be merging this feature in very shortly after some final polish.

**Comment by Css-IanM** [comment]
@colinskow That’s great news, I look forward to the update.

Ian Mackie
Lead Developer
Complete System Support, Inc.

**Comment by colinskow** [comment]
DONE!

**Pull request closed without merging**
